export const en = {
    Title: "Atlyn Network",
    ThirdPartyLicenses: "Third-party licenses",
    AvoidLabelOverlap: "Avoid overlapping labels", Exploration: "Exploration",
    InitialView: "Initial view", ViewAuto: "Automatic", ViewSplit: "Graph and list",
    InitialLayout: "Initial layout", LayoutChoice: "Layout (local only)",
    LayoutForce: "Force", LayoutCircular: "Circular", LayoutRadial: "Radial",
    RadialCenter: "Radial center (local only)", AutomaticCenter: "Automatic center",
    CenterNode: "Use as radial center", EffectiveCenter: "Layout center", ComponentCenters: "Separate component centers",
    MissingCenter: "Requested center is not loaded; automatic center shown. The requested center is retained.",
    CircularHelp: "One circle in stable ID order; angle and proximity do not encode distance or importance.",
    RadialHelp: "Rings show minimum undirected hops in loaded relationships, ignoring weights. Arrows still show original direction. Each disconnected component has its own center.",
    AutomaticCenterHelp: "Automatic center: largest component, most distinct neighbors, stable ID tie break. A layout convenience, not centrality or business importance.",
    InvalidLayout: "Invalid layout setting; Force is shown. Choose Force, Circular or Radial.",
    CameraReset: "Saved geometry differs from the loaded layout; the camera was fitted without changing report selection.",
    LegacyView: "Version 1 local view restored in Force layout; its unversioned camera was fitted.",
    SaveTooLarge: "Local view cannot be saved: invalid state or more than 4,096 encoded characters. Shorten the search or use shorter IDs; nothing was stored.",
    ViewGraph: "Graph", ViewList: "List", ToggleView: "Switch graph/list view",
    Controls: "Explore and camera", Incident: "Loaded incident relationships",
    Path: "One shortest loaded directed path", PathTarget: "Path destination (local only)",
    NoPath: "No directed path exists in the loaded topology between these entities.",
    PathHelp: "One fewest-edge directed path; ties use stable relationship IDs. This is not an impact prediction.",
    SaveView: "Save local view", SavedView: "Local view requested for report storage. Save the report or update a Power BI bookmark to retain it.",
    BadSavedView: "Saved local view is invalid or no longer matches loaded entities. Local focus was reset.",
    SaveFailed: "Power BI could not store the local view.",
    Incoming: "incoming", Outgoing: "outgoing", IncidentCount: "loaded incident relationships",
    ShowIncident: "Inspect incident relationships", LabelsShown: "labels shown",
    DenseHelp: "Dense overview: zoom, focus an entity, or use the relationship list for exact edges.",
    MicroHelp: "Enlarge for the graph; the list remains available.",
    Visible: "Locally shown", SelectionBusy: "A report selection is pending. Try again after Power BI responds.",
    InteractionsDisabled: "Report interactions are disabled by this host; local exploration is available.",
    OverflowWeight: "Weight total exceeds the supported numeric range; unavailable",
    TooltipLimit: "Some tooltip data exceeds supported text/field limits and is explicitly unavailable; relationships are retained.",
    NumberId: "number ID", TextId: "text ID",
    TooltipFailed: "Power BI tooltips are unavailable. Use the relationship list to inspect the delivered values.",
    Role_Source: "Source ID", Role_Target: "Target ID", Role_Weight: "Weight",
    Role_Type: "Relationship type", Role_Edge: "Edge ID", Role_Tooltips: "Tooltips",
    Appearance: "Appearance", NodeColor: "Entity color", EdgeColor: "Relationship color",
    ShowLabels: "Show entity labels", LabelSize: "Label size",
    Search: "Search loaded entities", Entity: "Focus entity (local only)",
    All: "All loaded topology", Neighbors: "Loaded neighborhood", Upstream: "Loaded upstream traversal",
    Downstream: "Loaded downstream traversal", FocusMode: "Local focus mode",
    Fit: "Fit", ZoomIn: "Zoom in", ZoomOut: "Zoom out", ResetFocus: "Reset local focus",
    ClearSelection: "Clear report selection", Entities: "Entities", Relationships: "Relationships",
    SelectNode: "Select loaded incident relationships", SelectEdge: "Select relationship",
    Focus: "Focus locally", Previous: "Previous", Next: "Next", Page: "Page",
    Bind: "Add Source ID and Target ID to display directed relationships. Weight, relationship type, edge ID and tooltips are optional.",
    Empty: "No valid relationships in the supplied data.",
    Loading: "Loading supplied relationships...",
    Incomplete: "Topology incomplete. Search, traversal and counts cover only loaded relationships.",
    Loaded: "Loaded", EntityCount: "entities", EdgeCount: "relationships",
    InvalidIds: "Rows omitted: invalid or missing IDs",
    Duplicates: "Repeated relationship rows aggregated",
    Ambiguous: "Conflicting edge IDs omitted entirely",
    MissingWeights: "Missing/invalid weight contributions (relationships retained)",
    OmittedRows: "Rows over input cap", OmittedEdges: "Relationships over topology caps",
    MissingIdentities: "Some native identities unavailable; affected selections are disabled.",
    SelectionLimit: "Selection refused: more than 200 native relationship identities. Select a smaller relationship group; no subset was selected.",
    SelectionMissing: "Selection unavailable: complete native identities were not supplied for these relationships.",
    SelectionFailed: "Power BI could not apply this selection. Try again in the native host.",
    ContextFailed: "Power BI could not open the context menu.",
    RenderFailed: "Network could not render. Review the field bindings and supported data limits.",
    InvalidAppearance: "Invalid appearance values; safe default colors or label size are displayed. Use hexadecimal colors and a label size from 8 to 24.",
    ContextScope: "Entity and aggregated-relationship context menus are visual-level; no arbitrary relationship identity is used.",
    SelectionHelp: "Entity activation selects its loaded incident relationships, not an entity-level filter. Ctrl/Cmd uses native relationship multiselect. Local focus never filters the report.",
    GraphHelp: "Directed relationship graph. Drag background to pan; wheel or +/- to zoom; arrow keys to pan; Home to fit. Use the accessible lists for all loaded entities and relationships.",
    Source: "Source", Target: "Target", Type: "Type", Weight: "Weight", Highlight: "Highlighted weight",
    IncompleteWeight: "Incomplete weight (known contribution)",
    Unweighted: "Unweighted", Missing: "Unavailable", Multiple: "Multiple delivered values",
    Rows: "Contributing rows", NoResults: "No matching loaded entities.",
    FocusNotice: "Local focus only; traversal does not predict business impact.",
    PartialSelection: "Some contributing relationships selected",
    Selected: "Selected", NoSelection: "Not selected", Details: "Relationship details"
};

export type MessageKey = keyof typeof en;

export const ar: Record<MessageKey, string> = {
    Title: "شبكة أتلين",
    ThirdPartyLicenses: "تراخيص الجهات الخارجية",
    AvoidLabelOverlap: "تجنّب تداخل التسميات", Exploration: "الاستكشاف",
    InitialView: "العرض الأولي", ViewAuto: "تلقائي", ViewSplit: "الرسم والقائمة",
    InitialLayout: "التخطيط الأولي", LayoutChoice: "التخطيط (محلي فقط)",
    LayoutForce: "القوى", LayoutCircular: "دائري", LayoutRadial: "شعاعي",
    RadialCenter: "المركز الشعاعي (محلي فقط)", AutomaticCenter: "مركز تلقائي",
    CenterNode: "استخدام كمركز شعاعي", EffectiveCenter: "مركز التخطيط", ComponentCenters: "مراكز المكونات المنفصلة",
    MissingCenter: "المركز المطلوب غير محمّل؛ يُعرض مركز تلقائي. تم الاحتفاظ بالمركز المطلوب.",
    CircularHelp: "دائرة واحدة بترتيب المعرّفات الثابت. الزاوية والتقارب لا يدلان على المسافة أو الأهمية.",
    RadialHelp: "الحلقات تمثل أقل عدد من الخطوات غير الموجّهة في العلاقات المحمّلة دون الأوزان. الأسهم تبين الاتجاه الأصلي. لكل مكوّن منفصل مركزه.",
    AutomaticCenterHelp: "المركز التلقائي: أكبر مكوّن ثم أكثر الجيران المختلفين ثم المعرّف الثابت عند التعادل. وسيلة تخطيط وليست مقياس مركزية أو أهمية تجارية.",
    InvalidLayout: "إعداد تخطيط غير صالح؛ يُعرض تخطيط القوى. اختر القوى أو الدائري أو الشعاعي.",
    CameraReset: "هندسة العرض المحفوظ تختلف عن التخطيط المحمّل؛ تمت ملاءمة الكاميرا دون تغيير تحديد التقرير.",
    LegacyView: "استُعيد العرض المحلي بالإصدار 1 في تخطيط القوى مع ملاءمة الكاميرا القديمة.",
    SaveTooLarge: "تعذّر حفظ العرض: حالة غير صالحة أو أكثر من 4096 محرفًا بعد الترميز. قصّر البحث أو المعرّفات؛ لم يُحفظ شيء.",
    ViewGraph: "الرسم", ViewList: "القائمة", ToggleView: "تبديل عرض الرسم والقائمة",
    Controls: "الاستكشاف والكاميرا", Incident: "العلاقات المحمّلة المتصلة",
    Path: "أقصر مسار موجّه محمّل واحد", PathTarget: "وجهة المسار (محلي فقط)",
    NoPath: "لا يوجد مسار موجّه بين هذين الكيانين في العلاقات المحمّلة.",
    PathHelp: "مسار موجّه بأقل عدد من العلاقات؛ التعادل حسب المعرّفات الثابتة. ليس تنبؤًا بالأثر.",
    SaveView: "حفظ العرض المحلي", SavedView: "طُلب حفظ العرض محليًا في خصائص التقرير. احفظ التقرير أو حدّث إشارة مرجعية في Power BI للاحتفاظ به.",
    BadSavedView: "العرض المحفوظ غير صالح أو لا يطابق الكيانات المحمّلة. أُعيد ضبط التركيز.",
    SaveFailed: "تعذّر تخزين العرض المحلي في Power BI.",
    Incoming: "واردة", Outgoing: "صادرة", IncidentCount: "علاقات محمّلة متصلة",
    ShowIncident: "فحص العلاقات المتصلة", LabelsShown: "تسميات معروضة",
    DenseHelp: "عرض كثيف: كبّر أو ركّز على كيان أو استخدم قائمة العلاقات للتحديد الدقيق.",
    MicroHelp: "كبّر المرئي للرسم؛ القائمة متاحة.",
    Visible: "معروض محليًا", SelectionBusy: "تحديد التقرير قيد التنفيذ. حاول بعد استجابة Power BI.",
    InteractionsDisabled: "تفاعلات التقرير معطّلة في المضيف؛ الاستكشاف المحلي متاح.",
    OverflowWeight: "مجموع الأوزان يتجاوز النطاق العددي المدعوم؛ غير متاح",
    TooltipLimit: "تتجاوز بعض التلميحات حدود النص أو الحقول وهي غير متاحة صراحةً؛ تم الاحتفاظ بالعلاقات.",
    NumberId: "معرّف رقمي", TextId: "معرّف نصي",
    TooltipFailed: "تلميحات Power BI غير متاحة. استخدم قائمة العلاقات لفحص القيم المقدّمة.",
    Role_Source: "معرّف المصدر", Role_Target: "معرّف الهدف", Role_Weight: "الوزن",
    Role_Type: "نوع العلاقة", Role_Edge: "معرّف العلاقة", Role_Tooltips: "تلميحات",
    Appearance: "المظهر", NodeColor: "لون الكيان", EdgeColor: "لون العلاقة",
    ShowLabels: "إظهار أسماء الكيانات", LabelSize: "حجم التسمية",
    Search: "البحث في الكيانات المحمّلة", Entity: "كيان التركيز (محلي فقط)",
    All: "كل العلاقات المحمّلة", Neighbors: "الجوار المحمّل", Upstream: "تتبّع المصادر المحمّلة",
    Downstream: "تتبّع الأهداف المحمّلة", FocusMode: "وضع التركيز المحلي",
    Fit: "ملاءمة", ZoomIn: "تكبير", ZoomOut: "تصغير", ResetFocus: "إعادة التركيز المحلي",
    ClearSelection: "مسح تحديد التقرير", Entities: "الكيانات", Relationships: "العلاقات",
    SelectNode: "تحديد العلاقات المحمّلة المتصلة", SelectEdge: "تحديد العلاقة",
    Focus: "تركيز محلي", Previous: "السابق", Next: "التالي", Page: "صفحة",
    Bind: "أضف معرّف المصدر ومعرّف الهدف لعرض العلاقات الموجّهة. الوزن ونوع العلاقة ومعرّفها والتلميحات اختيارية.",
    Empty: "لا توجد علاقات صالحة في البيانات المقدّمة.",
    Loading: "جارٍ تحميل العلاقات المقدّمة...",
    Incomplete: "البنية غير مكتملة. البحث والتتبّع والأعداد تخص العلاقات المحمّلة فقط.",
    Loaded: "محمّل", EntityCount: "كيانات", EdgeCount: "علاقات",
    InvalidIds: "صفوف مستبعدة: معرّفات غير صالحة أو مفقودة",
    Duplicates: "تم تجميع صفوف العلاقات المكرّرة",
    Ambiguous: "معرّفات علاقات متعارضة مستبعدة بالكامل",
    MissingWeights: "أوزان مفقودة أو غير صالحة (تم الاحتفاظ بالعلاقات)",
    OmittedRows: "صفوف تتجاوز حد الإدخال", OmittedEdges: "علاقات تتجاوز حدود البنية",
    MissingIdentities: "بعض هويات التحديد غير متاحة؛ تحديد العلاقات المتأثرة غير متاح.",
    SelectionLimit: "رُفض التحديد: أكثر من 200 هوية علاقة. اختر مجموعة أصغر؛ لم يتم تحديد جزء منها.",
    SelectionMissing: "التحديد غير متاح: لم تُقدّم هويات أصلية كاملة لهذه العلاقات.",
    SelectionFailed: "تعذّر تطبيق التحديد في Power BI. أعد المحاولة في المضيف الأصلي.",
    ContextFailed: "تعذّر فتح قائمة السياق في Power BI.",
    RenderFailed: "تعذّر عرض الشبكة. راجع ربط الحقول وحدود البيانات المدعومة.",
    InvalidAppearance: "قيم مظهر غير صالحة؛ تُعرض الألوان أو الأحجام الافتراضية الآمنة. استخدم ألوانًا سداسية عشرية وحجم تسمية من 8 إلى 24.",
    ContextScope: "قوائم سياق الكيانات والعلاقات المجمّعة تخص المرئي ككل؛ لا تُستخدم هوية علاقة عشوائية.",
    SelectionHelp: "تنشيط الكيان يحدّد علاقاته المحمّلة المتصلة، وليس تصفية على مستوى الكيان. يستخدم Ctrl/Cmd التحديد المتعدد الأصلي للعلاقات. التركيز المحلي لا يصفّي التقرير.",
    GraphHelp: "شبكة علاقات موجّهة. اسحب الخلفية للتحريك؛ استخدم العجلة أو +/- للتكبير؛ الأسهم للتحريك؛ Home للملاءمة. استخدم القوائم للوصول إلى كل الكيانات والعلاقات المحمّلة.",
    Source: "المصدر", Target: "الهدف", Type: "النوع", Weight: "الوزن", Highlight: "الوزن المميّز",
    IncompleteWeight: "وزن غير مكتمل (المساهمة المعروفة)",
    Unweighted: "دون وزن", Missing: "غير متاح", Multiple: "قيم مقدّمة متعددة",
    Rows: "الصفوف المساهمة", NoResults: "لا توجد كيانات محمّلة مطابقة.",
    FocusNotice: "تركيز محلي فقط؛ التتبّع لا يتنبّأ بالأثر التجاري.",
    PartialSelection: "بعض العلاقات المساهمة محدّدة",
    Selected: "محدّد", NoSelection: "غير محدّد", Details: "تفاصيل العلاقة"
};
