export const en = {
    Title: "Atlyn Network",
    ThirdPartyLicenses: "Third-party licenses",
    Role_Source: "Source ID", Role_Target: "Target ID", Role_Weight: "Weight",
    Role_Type: "Relationship type", Role_Edge: "Edge ID", Role_Tooltips: "Tooltips",
    Appearance: "Appearance", NodeColor: "Entity color", EdgeColor: "Relationship color",
    ShowLabels: "Show entity labels", LabelSize: "Label size",
    Search: "Search loaded entities", Entity: "Focus entity (local only)",
    All: "All loaded topology", Neighbors: "Loaded neighborhood", Upstream: "Loaded upstream traversal",
    Downstream: "Loaded downstream traversal", FocusMode: "Local focus mode",
    Fit: "Fit", ZoomIn: "Zoom in", ZoomOut: "Zoom out", ResetFocus: "Reset local focus",
    ClearSelection: "Clear report selection", Entities: "Entities", Relationships: "Relationships",
    SelectNode: "Select loaded incident relationships", SelectEdge: "Select relationship",
    Focus: "Focus locally", Previous: "Previous", Next: "Next", Page: "Page",
    Bind: "Add Source ID and Target ID to display directed relationships. Weight, relationship type, edge ID and tooltips are optional.",
    Empty: "No valid relationships in the supplied data.",
    Loading: "Loading supplied relationships...",
    Incomplete: "Topology incomplete. Search, traversal and counts cover only loaded relationships.",
    Loaded: "Loaded", EntityCount: "entities", EdgeCount: "relationships",
    InvalidIds: "Rows omitted: invalid or missing IDs",
    Duplicates: "Repeated relationship rows aggregated",
    Ambiguous: "Conflicting edge IDs omitted entirely",
    MissingWeights: "Missing/invalid weight contributions (relationships retained)",
    OmittedRows: "Rows over input cap", OmittedEdges: "Relationships over topology caps",
    MissingIdentities: "Some native identities unavailable; affected selections are disabled.",
    SelectionLimit: "Selection refused: more than 200 native relationship identities. Select a smaller relationship group; no subset was selected.",
    SelectionMissing: "Selection unavailable: complete native identities were not supplied for these relationships.",
    SelectionFailed: "Power BI could not apply this selection. Try again in the native host.",
    ContextFailed: "Power BI could not open the context menu.",
    RenderFailed: "Network could not render. Review the field bindings and supported data limits.",
    InvalidAppearance: "Invalid appearance values; safe default colors or label size are displayed. Use hexadecimal colors and a label size from 8 to 24.",
    ContextScope: "Entity and aggregated-relationship context menus are visual-level; no arbitrary relationship identity is used.",
    SelectionHelp: "Entity activation selects its loaded incident relationships, not an entity-level filter. Ctrl/Cmd uses native relationship multiselect. Local focus never filters the report.",
    GraphHelp: "Directed relationship graph. Drag background to pan; wheel or +/- to zoom; arrow keys to pan; Home to fit. Use the accessible lists for all loaded entities and relationships.",
    Source: "Source", Target: "Target", Type: "Type", Weight: "Weight", Highlight: "Highlighted weight",
    IncompleteWeight: "Incomplete weight (known contribution)",
    Unweighted: "Unweighted", Missing: "Unavailable", Multiple: "Multiple delivered values",
    Rows: "Contributing rows", NoResults: "No matching loaded entities.",
    FocusNotice: "Local focus only; traversal does not predict business impact.",
    PartialSelection: "Some contributing relationships selected",
    Selected: "Selected", NoSelection: "Not selected", Details: "Relationship details"
};

export type MessageKey = keyof typeof en;

export const ar: Record<MessageKey, string> = {
    Title: "شبكة أتلين",
    ThirdPartyLicenses: "تراخيص الجهات الخارجية",
    Role_Source: "معرّف المصدر", Role_Target: "معرّف الهدف", Role_Weight: "الوزن",
    Role_Type: "نوع العلاقة", Role_Edge: "معرّف العلاقة", Role_Tooltips: "تلميحات",
    Appearance: "المظهر", NodeColor: "لون الكيان", EdgeColor: "لون العلاقة",
    ShowLabels: "إظهار أسماء الكيانات", LabelSize: "حجم التسمية",
    Search: "البحث في الكيانات المحمّلة", Entity: "كيان التركيز (محلي فقط)",
    All: "كل العلاقات المحمّلة", Neighbors: "الجوار المحمّل", Upstream: "تتبّع المصادر المحمّلة",
    Downstream: "تتبّع الأهداف المحمّلة", FocusMode: "وضع التركيز المحلي",
    Fit: "ملاءمة", ZoomIn: "تكبير", ZoomOut: "تصغير", ResetFocus: "إعادة التركيز المحلي",
    ClearSelection: "مسح تحديد التقرير", Entities: "الكيانات", Relationships: "العلاقات",
    SelectNode: "تحديد العلاقات المحمّلة المتصلة", SelectEdge: "تحديد العلاقة",
    Focus: "تركيز محلي", Previous: "السابق", Next: "التالي", Page: "صفحة",
    Bind: "أضف معرّف المصدر ومعرّف الهدف لعرض العلاقات الموجّهة. الوزن ونوع العلاقة ومعرّفها والتلميحات اختيارية.",
    Empty: "لا توجد علاقات صالحة في البيانات المقدّمة.",
    Loading: "جارٍ تحميل العلاقات المقدّمة...",
    Incomplete: "البنية غير مكتملة. البحث والتتبّع والأعداد تخص العلاقات المحمّلة فقط.",
    Loaded: "محمّل", EntityCount: "كيانات", EdgeCount: "علاقات",
    InvalidIds: "صفوف مستبعدة: معرّفات غير صالحة أو مفقودة",
    Duplicates: "تم تجميع صفوف العلاقات المكرّرة",
    Ambiguous: "معرّفات علاقات متعارضة مستبعدة بالكامل",
    MissingWeights: "أوزان مفقودة أو غير صالحة (تم الاحتفاظ بالعلاقات)",
    OmittedRows: "صفوف تتجاوز حد الإدخال", OmittedEdges: "علاقات تتجاوز حدود البنية",
    MissingIdentities: "بعض هويات التحديد غير متاحة؛ تحديد العلاقات المتأثرة غير متاح.",
    SelectionLimit: "رُفض التحديد: أكثر من 200 هوية علاقة. اختر مجموعة أصغر؛ لم يتم تحديد جزء منها.",
    SelectionMissing: "التحديد غير متاح: لم تُقدّم هويات أصلية كاملة لهذه العلاقات.",
    SelectionFailed: "تعذّر تطبيق التحديد في Power BI. أعد المحاولة في المضيف الأصلي.",
    ContextFailed: "تعذّر فتح قائمة السياق في Power BI.",
    RenderFailed: "تعذّر عرض الشبكة. راجع ربط الحقول وحدود البيانات المدعومة.",
    InvalidAppearance: "قيم مظهر غير صالحة؛ تُعرض الألوان أو الأحجام الافتراضية الآمنة. استخدم ألوانًا سداسية عشرية وحجم تسمية من 8 إلى 24.",
    ContextScope: "قوائم سياق الكيانات والعلاقات المجمّعة تخص المرئي ككل؛ لا تُستخدم هوية علاقة عشوائية.",
    SelectionHelp: "تنشيط الكيان يحدّد علاقاته المحمّلة المتصلة، وليس تصفية على مستوى الكيان. يستخدم Ctrl/Cmd التحديد المتعدد الأصلي للعلاقات. التركيز المحلي لا يصفّي التقرير.",
    GraphHelp: "شبكة علاقات موجّهة. اسحب الخلفية للتحريك؛ استخدم العجلة أو +/- للتكبير؛ الأسهم للتحريك؛ Home للملاءمة. استخدم القوائم للوصول إلى كل الكيانات والعلاقات المحمّلة.",
    Source: "المصدر", Target: "الهدف", Type: "النوع", Weight: "الوزن", Highlight: "الوزن المميّز",
    IncompleteWeight: "وزن غير مكتمل (المساهمة المعروفة)",
    Unweighted: "دون وزن", Missing: "غير متاح", Multiple: "قيم مقدّمة متعددة",
    Rows: "الصفوف المساهمة", NoResults: "لا توجد كيانات محمّلة مطابقة.",
    FocusNotice: "تركيز محلي فقط؛ التتبّع لا يتنبّأ بالأثر التجاري.",
    PartialSelection: "بعض العلاقات المساهمة محدّدة",
    Selected: "محدّد", NoSelection: "غير محدّد", Details: "تفاصيل العلاقة"
};
